### ISSUE TITLE
Does Not Work Out Of The Box

### ISSUE THREAD

**Issue by firezdog** [o19s/agent_q#17]
I wouldn't normally consider it an issue for an application not to work out of the box when pulling down the github repo, but the readme doesn't have any instructions / suggestions concerning installation of dependencies.  Just doing the most naive pull of the repo and putting the suggested command into my cli, I get the following error:

Traceback (most recent call last):
        4: from ./local_es_search_poc/quepid/agent_q/bin/agent_q:3:in `<main>'
        3: from ./local_es_search_poc/quepid/agent_q/bin/agent_q:3:in `require_relative'
        2: from /Users/xaxl172/code/zoro-search/local_es_search_poc/quepid/agent_q/lib/agent_q.rb:4:in `<top (required)>'
        1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- capybara (LoadError)

If there is some required version of ruby etc. that needs to be installed to run the application, either an install script should be created or instructions on what is required should be included in the readme.

**Comment by firezdog** [comment]
It seems like this will work with an installation of Chrome in say a Docker container -- but a small modification to Capybara was required to allow the browser to run with no sandbox (at least for Docker).  The README mentions using / installing PhantomJS but does not elaborate on what needs to be done with it -- in the Docker setup I mentioned we didn't seem to need PhantomJS at all (unless it is already being installed by the Gem).
